# Site settings
baseurl = "http://example.org/"
languageCode = "de-DE"
title = "StatistikWerkstatt Leipzig"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
#googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "StatistikWerkstatt Leipzig"
    subtitle = "Statistik statt Räder - offene Selbsthilfewerkstatt für statistische Fragen&Probleme"
    author = "George Black"
    description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "Hugo, Statistik, Leipzig"

    # Body background color
	  #bodybgcolor = "#f9f9f9" white
    bodybgcolor = "#dbb569"

    # Preview container button text
    buttontext = "Zurück zur Seite"

    # Footer text
    footertext = "Created with [Hugo](http://gohugo.io) and a theme from [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/) and [aerohub](https://github.com/aerohub)<br>Hosted on a eco-friendly server by [manitu](https://www.manitu.de/)"
