# Site settings
#to-do: refugees thumb ersetzen
baseurl = "http://statistikwerkstatt.org/"
languageCode = "de-DE"
title = "StatistikWerkstatt Leipzig"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-88567681-1"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "StatistikWerkstatt Leipzig"
    subtitle = "Offene Selbsthilfewerkstatt für statistische Fragen&Probleme"
    author = "George Black"
    description = "Offene Selbsthilfewerkstatt für statistische Fragen&Probleme im Leipziger Westen"
    keywords = "Hilfe, Statistik, Leipzig, Nachhilfe, Daten, Auswertung, Statistics"

    # Body background color
	  #bodybgcolor = "#ddd"
    bodybgcolor = "#dbb569"# old
    #bodytextcolor = "#dbb569"

    # Preview container button text
    buttontext = "Zurück zur Seite"

    # Footer text
    footertext = "Created with [Hugo](http://gohugo.io) and a theme from [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/) and [aerohub](https://github.com/aerohub)<br>Hosted on an eco-friendly server by [manitu](https://www.manitu.de/)<br>[Imprint](http://www.statistikwerkstatt.org/impressum.html)"
